// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNLLafxwn4hnjGfoCVBdFpnUBUhG56tZ8',
    appId: '1:677846422589:web:ef9a46e6f21cf4503bc654',
    messagingSenderId: '677846422589',
    projectId: 'itss2-914b5',
    authDomain: 'itss2-914b5.firebaseapp.com',
    databaseURL: 'https://itss2-914b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itss2-914b5.appspot.com',
    measurementId: 'G-L7D2Z2P3Z1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA3aOe6614ctM490PzmNl99vSIjQfGH9Q',
    appId: '1:677846422589:android:389a2f7335046b3c3bc654',
    messagingSenderId: '677846422589',
    projectId: 'itss2-914b5',
    databaseURL: 'https://itss2-914b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itss2-914b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFMuCgZ2B2J9BgoOJzlarAlzq0QsAaDOc',
    appId: '1:677846422589:ios:022b162074f0e6cb3bc654',
    messagingSenderId: '677846422589',
    projectId: 'itss2-914b5',
    databaseURL: 'https://itss2-914b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itss2-914b5.appspot.com',
    iosBundleId: 'com.example.translateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFMuCgZ2B2J9BgoOJzlarAlzq0QsAaDOc',
    appId: '1:677846422589:ios:022b162074f0e6cb3bc654',
    messagingSenderId: '677846422589',
    projectId: 'itss2-914b5',
    databaseURL: 'https://itss2-914b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itss2-914b5.appspot.com',
    iosBundleId: 'com.example.translateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNLLafxwn4hnjGfoCVBdFpnUBUhG56tZ8',
    appId: '1:677846422589:web:d5ba216c640037603bc654',
    messagingSenderId: '677846422589',
    projectId: 'itss2-914b5',
    authDomain: 'itss2-914b5.firebaseapp.com',
    databaseURL: 'https://itss2-914b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'itss2-914b5.appspot.com',
    measurementId: 'G-XKJD0E02NK',
  );
}
